-- Create foods table
CREATE TABLE foods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    protein DECIMAL(10,2) NOT NULL,
    calories INTEGER NOT NULL,
    unit VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create dailydiet table
CREATE TABLE dailydiet (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    food_id BIGINT REFERENCES foods(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create indexes for better performance
CREATE INDEX idx_foods_name ON foods(name);
CREATE INDEX idx_dailydiet_date ON dailydiet(date);
CREATE INDEX idx_dailydiet_food_id ON dailydiet(food_id);

-- Set up Row Level Security (RLS)
ALTER TABLE foods ENABLE ROW LEVEL SECURITY;
ALTER TABLE dailydiet ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Enable read access for all users" ON foods
    FOR SELECT USING (true);

CREATE POLICY "Enable insert for all users" ON foods
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Enable delete for all users" ON foods
    FOR DELETE USING (true);

CREATE POLICY "Enable read access for all users" ON dailydiet
    FOR SELECT USING (true);

CREATE POLICY "Enable insert for all users" ON dailydiet
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Enable delete for all users" ON dailydiet
    FOR DELETE USING (true); 